version: 2

project_name: aether

before:
  hooks:
    - go mod tidy
    # Hub 在编译时通过 go:embed 读取 internal/site/dist；该目录为构建产物且不入库。
    # 为避免发布时缺失/陈旧的前端资源，发布流程需先构建 Web UI。
    - make build-web-ui

builds:
  - id: aether
    binary: aether
    main: internal/cmd/hub/hub.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm

  - id: aether-agent
    binary: aether-agent
    main: internal/cmd/agent/agent.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - mips64
      - riscv64
      - mipsle
      - mips
      - ppc64le
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: linux
        goarch: mips64
        gomips: softfloat
      - goos: linux
        goarch: mipsle
        gomips: hardfloat
      - goos: linux
        goarch: mips
        gomips: hardfloat
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: mips64
      - goos: windows
        goarch: mipsle
      - goos: windows
        goarch: mips
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: riscv64
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: mips64
      - goos: darwin
        goarch: mipsle
      - goos: darwin
        goarch: mips
      - goos: darwin
        goarch: ppc64le
      - goos: windows
        goarch: riscv64
      - goos: freebsd
        goarch: mips64
      - goos: freebsd
        goarch: mipsle
      - goos: freebsd
        goarch: mips
      - goos: freebsd
        goarch: ppc64le
      - goos: openbsd
        goarch: mips64
      - goos: openbsd
        goarch: mipsle
      - goos: openbsd
        goarch: mips
      - goos: openbsd
        goarch: ppc64le

archives:
  - id: aether-agent
    formats: [tar.gz]
    ids:
      - aether-agent
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: aether
    formats: [tar.gz]
    ids:
      - aether
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "aether_{{ .Version }}_checksums.txt"
  algorithm: sha256

nfpms:
  - id: aether-agent
    package_name: aether-agent
    description: |-
      Agent for Aether
      Aether 是轻量服务器监控平台，包含 Docker 统计、历史数据与告警。
      具备友好 Web 界面、开箱即用的配置，并支持多用户、OAuth 与 API 访问。
    maintainer: loboyanzy
    section: net
    ids:
      - aether-agent
    formats:
      - deb
    contents:
      - src: ./supplemental/debian/aether-agent.service
        dst: lib/systemd/system/aether-agent.service
        packager: deb
      - src: ./supplemental/debian/copyright
        dst: usr/share/doc/aether-agent/copyright
        packager: deb
      - src: ./supplemental/debian/lintian-overrides
        dst: usr/share/lintian/overrides/aether-agent
        packager: deb
    scripts:
      postinstall: ./supplemental/debian/postinstall.sh
      preremove: ./supplemental/debian/prerm.sh
      postremove: ./supplemental/debian/postrm.sh
    deb:
      predepends:
        - adduser
        - debconf
      scripts:
        templates: ./supplemental/debian/templates
        # Currently broken due to a bug in goreleaser
        # https://github.com/goreleaser/goreleaser/issues/5487
        #config: ./supplemental/debian/config.sh

  - id: aether
    package_name: aether
    description: |-
      Hub for Aether
      Aether 是轻量服务器监控平台，包含 Docker 统计、历史数据与告警。
      具备友好 Web 界面、开箱即用的配置，并支持多用户、OAuth 与 API 访问。
    maintainer: loboyanzy
    section: net
    ids:
      - aether
    formats:
      - deb
    contents:
      - src: ./supplemental/debian/aether.service
        dst: lib/systemd/system/aether.service
        packager: deb
      - src: ./supplemental/debian/copyright
        dst: usr/share/doc/aether/copyright
        packager: deb
    scripts:
      postinstall: ./supplemental/debian/aether-postinstall.sh
      preremove: ./supplemental/debian/aether-prerm.sh
      postremove: ./supplemental/debian/aether-postrm.sh
    deb:
      predepends:
        - adduser

scoops:
  - ids: [aether-agent]
    name: aether-agent
    repository:
      owner: LuBoyanzy
      name: aether-scoops
    homepage: "https://github.com/LuBoyanzy/Aether"
    description: "Agent for Aether，轻量服务器监控平台。"
    license: MIT
    # The target Scoop repo isn't guaranteed to exist; keep releases unblocked by default.
    skip_upload: true


brews:
  - ids: [aether-agent]
    name: aether-agent
    repository:
      owner: LuBoyanzy
      name: homebrew-aether
    homepage: "https://github.com/LuBoyanzy/Aether"
    description: "Agent for Aether，轻量服务器监控平台。"
    license: MIT
    # The target Homebrew tap repo isn't guaranteed to exist; keep releases unblocked by default.
    skip_upload: true
    extra_install: |
      (bin/"aether-agent-launcher").write <<~EOS
        #!/bin/bash
        set -a
        if [ -f "$HOME/.config/aether/aether-agent.env" ]; then
          source "$HOME/.config/aether/aether-agent.env"
        fi
        set +a
        exec #{bin}/aether-agent "$@"
      EOS
      (bin/"aether-agent-launcher").chmod 0755
    service: |
      run ["#{bin}/aether-agent-launcher"]
      log_path "#{Dir.home}/.cache/aether/aether-agent.log"
      error_log_path "#{Dir.home}/.cache/aether/aether-agent.log"
      keep_alive true
      restart_delay 5
      process_type :background

winget:
  - ids: [aether-agent]
    name: aether-agent
    package_identifier: loboyanzy.aether-agent
    publisher: loboyanzy
    license: MIT
    license_url: "https://github.com/LuBoyanzy/Aether/blob/main/LICENSE"
    copyright: "2025 loboyanzy"
    homepage: "https://github.com/LuBoyanzy/Aether"
    release_notes_url: "https://github.com/LuBoyanzy/Aether/releases/tag/v{{ .Version }}"
    publisher_support_url: "https://github.com/LuBoyanzy/Aether/issues"
    short_description: "Agent for Aether，轻量服务器监控平台。"
    description: |
      Aether 是轻量服务器监控平台，包含 Docker 统计、历史数据与告警。
      具备友好 Web 界面、开箱即用的配置，并支持多用户、OAuth 与 API 访问。
    tags:
      - homelab
      - monitoring
      - self-hosted
    repository:
      owner: LuBoyanzy
      name: aether-winget
      branch: loboyanzy.aether-agent-{{ .Version }}
      token: "{{ .Env.WINGET_TOKEN }}"
      # pull_request:
      #   enabled: true
      #   draft: false
      #   base:
      #     owner: microsoft
      #     name: winget-pkgs
      #     branch: master
    # Requires a separate repo + token; keep releases unblocked by default.
    skip_upload: true

release:
  draft: false

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
