name: 🐛 Bug report
description: Report a new bug or issue.
title: '[Bug]: '
labels: ['bug', "needs confirmation"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Aether is this about?
      options:
        - Hub
        - Agent
        - Hub & Agent
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to fill out this bug report!

        - For more general support, please [start a support thread](https://github.com/LuBoyanzy/Aether/discussions).
        - To request a change or feature, use the [feature request form](https://github.com/LuBoyanzy/Aether/issues/new?template=feature_request.yml).
        - Please do not submit bugs that are specific to ZFS. We plan to add integration with ZFS utilities in the near future.

        ### Before submitting a bug report:

        - Check the [guides](https://github.com/LuBoyanzy/Aether/tree/main/supplemental/guides).
        - Search existing [issues](https://github.com/LuBoyanzy/Aether/issues) and [discussions](https://github.com/LuBoyanzy/Aether/discussions) (including closed).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain the issue you experienced clearly and concisely.
      placeholder: I went to the coffee pot and it was empty.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: In a perfect world, what should have happened?
      placeholder: When I got to the coffee pot, it should have been full.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the issue in repeatable steps.
      placeholder: |
        1. Go to the coffee pot.
        2. Make more coffee.
        3. Pour it into a cup.
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category does this relate to most?
      options:
        - Metrics
        - Charts & Visualization
        - Settings & Configuration
        - Notifications & Alerts
        - Authentication
        - Installation
        - Performance
        - UI / UX
        - Other
    validations:
      required: true
  - type: dropdown
    id: metrics
    attributes:
      label: Affected Metrics
      description: If applicable, which specific metric does this relate to most?
      options:
        - CPU
        - Memory
        - Storage
        - Network
        - Containers
        - GPU
        - Sensors
        - Other
    validations:
      required: true
  - type: input
    id: system
    attributes:
      label: OS / Architecture
      placeholder: linux/amd64 (agent), freebsd/arm64 (hub)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Aether version
      placeholder: 1.0.0
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      options:
        - Docker
        - Binary
        - Nix
        - Unraid
        - Coolify
        - Other (please describe above)
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please provide any relevant service configuration
      render: yaml
  - type: textarea
    id: hub-logs
    attributes:
      label: Hub Logs
      description: Check the logs page in PocketBase (`/_/#/logs`) for relevant errors (copy JSON).
      render: json
  - type: textarea
    id: agent-logs
    attributes:
      label: Agent Logs
      description: Please provide any logs from the agent, if relevant. Use `LOG_LEVEL=debug` for more info.
      render: shell
